# Do not edit this file, pipeline versioning is governed by git tags
# following PEP 386
__version__ = "1.0.6"

try:
    from django.core.exceptions import ImproperlyConfigured
    try:
        from .binding import AsyncBinding, bind
        from .consumer import AsyncConsumer
    except django.core.exceptions.ImproperlyConfigured as e:
        pass
except NameError as e:
    pass
