version: '3.6'
services:
    nginx:  
        command: /bin/bash -c "envsubst < /etc/nginx/envs/dev/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    back:
        volumes:
            - ./../packages/channels-binding-django/channels_binding:/usr/local/lib/python3.9/site-packages/channels_binding # VERY TEMP
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
    front: 
        volumes:
            - ./../packages/channels-binding-core/src:/tmp/channels-binding-core # VERY TEMP
        command: yarn run runserver
        restart: always
    worker:
        tty: true
        command: watchmedo auto-restart -R -p '*.py' -- ./worker.sh
