services:
    back:
        build: ./back
        command: python manage.py runserver 0.0.0.0:8000
        container_name: channels-binding.docs.localhost.back
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        links: &id001
        - postgres:postgres
        - redis:redis
        restart: always
        tty: true
        volumes:
        - ./back:/app
        - ./../packages/channels-binding-django/channels_binding:/usr/local/lib/python3.9/site-packages/channels_binding
    front:
        build: ./front
        command: yarn run runserver
        container_name: channels-binding.docs.localhost.front
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        restart: always
        volumes:
        - ./back:/back
        - ./../packages/channels-binding-core/src:/tmp/channels-binding-core
        - ./front:/app
    nginx:
        command: /bin/bash -c "envsubst < /etc/nginx/templates/conf.dev.template >
            /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        container_name: channels-binding.docs.localhost.nginx
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        image: nginx
        links:
        - back:back
        - front:front
        ports:
        - ${PORT:-8111}:80
        restart: always
        volumes:
        - ./nginx/:/etc/nginx/templates/
        - ./front:/front
        - /var/storage/channels-binding/docs/static:/stg/static:ro
        - /var/storage/channels-binding/docs/media:/stg/media:ro
    postgres:
        container_name: channels-binding.docs.localhost.postgres
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        image: postgres:12
        restart: always
        volumes:
        - /dev/shm:/dev/shm
        - /var/storage/channels-binding/docs/postgres/:/var/lib/postgresql/data
    redis:
        container_name: channels-binding.docs.localhost.redis
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        image: redis:6
        restart: always
        volumes:
        - /var/storage/channels-binding/docs/redis/:/data
    worker:
        build: ./back
        command: watchmedo auto-restart -R -p '*.py' -- ./worker.sh
        container_name: channels-binding.docs.localhost.worker
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - PUBLIC_PATH=${PUBLIC_PATH:-/}
        - PYTHONBUFFERED=1
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            PUBLIC_PATH=${PUBLIC_PATH:-/} PYTHONBUFFERED=1 DISABLE_COLLECTSTATIC=1
            PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/} DOLLAR=$$ DOCKER_EMPEROR_HOSTS=
            DEBUG=2 POSTGRES_HOST_AUTH_METHOD=trust PORT=${PORT:-8111} DOCKER_COMPOSE_TIMEOUT=10000
        - PUBLIC_WS_PATH=${PUBLIC_WS_PATH:-/ws/}
        - DOLLAR=$$
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=2
        - POSTGRES_HOST_AUTH_METHOD=trust
        - PORT=${PORT:-8111}
        - DOCKER_COMPOSE_TIMEOUT=10000
        links: *id001
        restart: always
        tty: true
        volumes:
        - ./back:/app
version: '3.6'
volumes: {}
