services:
    back:
        build: back
        command: python manage.py runserver 0.0.0.0:8000
        container_name: channels-binding.docs.localhost.back
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - TZ=Europe/Paris
        - PYTHONBUFFERED=1
        - SOCK_PORT=8888
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            TZ=Europe/Paris PYTHONBUFFERED=1 SOCK_PORT=8888 DISABLE_COLLECTSTATIC=1
            DOCKER_EMPEROR_HOSTS= DEBUG=1 POSTGRES_HOST_AUTH_METHOD=trust
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=1
        - POSTGRES_HOST_AUTH_METHOD=trust
        image: channels-binding.docs.back
        links:
        - postgres:postgres
        - redis:redis
        ports:
        - 8000:8000
        restart: always
        tty: true
        volumes:
        - ./back:/app
        - ./front/dist:/front/dist
    front:
        build: front
        command: yarn run runserver
        container_name: channels-binding.docs.localhost.front
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - TZ=Europe/Paris
        - PYTHONBUFFERED=1
        - SOCK_PORT=8888
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            TZ=Europe/Paris PYTHONBUFFERED=1 SOCK_PORT=8888 DISABLE_COLLECTSTATIC=1
            DOCKER_EMPEROR_HOSTS= DEBUG=1 POSTGRES_HOST_AUTH_METHOD=trust
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=1
        - POSTGRES_HOST_AUTH_METHOD=trust
        image: channels-binding.docs.front
        ports:
        - 8888:8000
        restart: always
        volumes:
        - ./front/:/app
    postgres:
        container_name: channels-binding.docs.localhost.postgres
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - TZ=Europe/Paris
        - PYTHONBUFFERED=1
        - SOCK_PORT=8888
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            TZ=Europe/Paris PYTHONBUFFERED=1 SOCK_PORT=8888 DISABLE_COLLECTSTATIC=1
            DOCKER_EMPEROR_HOSTS= DEBUG=1 POSTGRES_HOST_AUTH_METHOD=trust
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=1
        - POSTGRES_HOST_AUTH_METHOD=trust
        image: postgres:12-alpine
        restart: always
        volumes:
        - /dev/shm:/dev/shm
        - /var/storage/channels-binding/docs/postgres/:/var/lib/postgresql/data
    redis:
        container_name: channels-binding.docs.localhost.redis
        environment:
        - DEV_MODE=1
        - STG=/var/storage/channels-binding/docs
        - TZ=Europe/Paris
        - PYTHONBUFFERED=1
        - SOCK_PORT=8888
        - DISABLE_COLLECTSTATIC=1
        - DOCKER_EMPEROR_ENVIRONMENT=DEV_MODE=1 STG=/var/storage/channels-binding/docs
            TZ=Europe/Paris PYTHONBUFFERED=1 SOCK_PORT=8888 DISABLE_COLLECTSTATIC=1
            DOCKER_EMPEROR_HOSTS= DEBUG=1 POSTGRES_HOST_AUTH_METHOD=trust
        - DOCKER_EMPEROR_HOSTS=
        - DEBUG=1
        - POSTGRES_HOST_AUTH_METHOD=trust
        image: redis:5.0.5-alpine
        restart: always
        volumes:
        - /var/storage/channels-binding/docs/redis/:/data
version: '3.6'
volumes: {}
